config/routes.rb
Rails.application.routes.draw do
  root              'static_pages#home'
  get  'about'   => 'static_pages#about'
  get  'answer'  => 'static_pages#answer'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "In the fullness of time, this will be a grid solver application that generates a four-by-four grid of random letters, then produces a list of all words that can be created from that grid. The rules are that you have to be able to connect the tiles the letters appear in (using adjacency, including diagonals), and each tile can be used only once."
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def answer
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_title(page_title = '')
    base_title = "Grid Solver"
    if page_title.empty?
      base_title
    else
      "#{page_title} · #{base_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    GridSolver by <a href="mailto:hawthorn@foobox.com">Frank J. Perricone</a>
  </small>
  <div align=right><%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %></div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "GridSolver", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home",   root_path  %></li>
        <li><%= link_to "About",  about_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Grid Solver</h1>
<p>This application solves a word puzzle proposed by <a href="http://sumofus.org/">SumOfUs</a> in a job application test. Here's their description of the problem:</p>

<font color="darkblue"><blockquote><p>We at SumOfUs really enjoy playing games, of many different types. One game we like playing involves a 4x4 grid of random letters, which are combined to make as many words as possible. For instance, given the following list of random letters:</p>

<tt>D G H I<br />
K L P S<br />
Y E U T<br />
E O R N</tt>

<p>Some of the words that might be found are:</p>

<tt><ul><li>SUPER</li>
<li>NUTS</li>
<li>KEY</li>
<li>RUST</li>
<li>HIPS</li>
<li>I</li>
</ul></tt>

<p>Each letter can be connected to any other letter, going up, down, left, right, or to any of the diagonal corners. Example code is provided in <a href="https://gist.github.com/EricBoersma/a81b6ece56f54125f458">this gist</a>. Your job is to write the game_word_search method such that when it is run at the end of that script, it will return strings of the words contained in any given matrix of Letter instances as quickly as possible. You may write this function in any major object-oriented programming language. Please include a comment at the top of the file indicating which language you are writing your code in.</p></blockquote></font>

<p>I've added the following clarifying rules to the design:</p>
<ul>
  <li>Each grid tile can be used only once in a single word. Thus, in the example grid above, SPURT is a valid word, but SPURTS is not. This also means the maximum word length is 16.</li>
  <li>When a word can be created by multiple valid paths (e.g., LYE in the above grid) it should be listed multiple times accordingly.</li>
</ul>

<p>Due to the time limit on the test on which the question appeared, I was not able to make a working solution, and instead presented <%= link_to "a psuedocode solution", answer_path %> that demonstrated understanding the problem, identifying the clarifications required, creating a solution, and ensuring the solution is reasonably efficient; but that wasn't in any particular language and thus wasn't ready to be compiled or interpreted. This site is a Ruby on Rails implementation of the solution I proposed there, mostly because I wanted to see it through.</p>

<p>- <a href="mailto:hawthorn@foobox.com">Frank J. Perricone</a></p>

<hr>

<h2>Acknowledgements</h2>

<ul>
  <li><a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a> by <a href="http://www.michaelhartl.com/">Michael Hartl</a></li>
  <li><a href="https://github.com/mhuggins/ruby-dictionary">ruby-dictionary gem</a> by <a href="https://github.com/mhuggins">mhuggins</a></li>
  <li><a href="https://github.com/atebits/Words">Letterpress's word list</a> maintained by <a href="https://github.com/atebits">atebits</a></li>
</ul>

<hr>

<h2>Still To Do</h2>
<ul>
  <li>Import the word list in the setup</li>
  <li>Revise the letter grid to not be fixed</li>
  <li>Generate button that populates the grid</li>
  <li>Solve button that solves the grid, and paginates the results or puts them in a scroll box</li>
</ul>

app/views/static_pages/answer.html.erb
<% provide(:title, "Answer") %>
<h1>My Answer</h1>
<p>This is what I wrote in response to the question. I had about 50 minutes left when I got to this question.</p>

<pre><code>// I came to this question with nowhere near enough time to complete it,
// and there's also a missing link in the test pointing to a gist of
// example code. So rather than provide nothing or something too incomplete
// to tell you anything about me, I'm providing some pseudocode that
// describes the algorithm well enough for you to get the idea that I have
// come up with a viable, reasonably optimized solution. Actually
// implementing it in a specific language is the bit I don't have time to
// do. (Though I will probably do it in Ruby on Rails later today, just
// because it's going to haunt my thoughts until I create it somewhere...)

string TheGrid[16];

// For simplicity of passing around arrays of positions, I'll be
// using an array of 16 positions. Row one is positions 0,1,2,3;
// row two is 4,5,6,7; etc.

//////////////////////////////////////////////////////////////////////////

// Converts a series of positions into a string
function PositionsToString(positions[]) {
  result = ""
  for each position in positions[]
    result += TheGrid[position]    // assuming string concatenation
  return result
}

//////////////////////////////////////////////////////////////////////////

// Given an array with a series of positions within the grid,
// and a presumed already-provided word list, tells if a word
// has been formed.
function IsAWord(positions[]) {
  if PositionsToString(positions) in WordList return true
  return false
}

//////////////////////////////////////////////////////////////////////////

int DirectionXDelta[] = {-1,  0,  1, -1, 1, -1, 0, 1}
int DirectionYDelta[] = {-1, -1. -1,  0, 0,  1, 1, 1}
// Figures out which position is adjacent to another in a
// given direction. Directions are:
//     0 1 2
//     3 X 4
//     5 6 7
// an array is faster than doing the math, and this is
// inside a frequently-executed function so a good place
// to throw away a few dozen bytes to gain that speed

//////////////////////////////////////////////////////////////////////////

// Returns a position in a given direction, or nil if that's
// outside the grid

function AdjacentLocation(position, direction) {

  // find the x/y location for the starting position
  x = position % 4
  y = position / 4
  // assuming C/C++/C#-like operations for integer division and modulo

  // shift by the direction's delta, and jump out if we've fallen off the grid
  x += DirectionXDelta[direction]
  if x<0 or x>3 return nil
  y += DirectionYDelta[direction]
  if y<0 or y>3 return nil

  // convert back to position
  return y*4+x

}

//////////////////////////////////////////////////////////////////////////

// Given a series of positions used so far and a direction,
// returns the position in that direction, but only if it's
// a valid position not already present in the list;
// this is used while recursing to avoid going around in loops
// and thus having endless recursion. The assumption, which
// isn't explicitly stated in the problem but is implied by
// the sample answers, is that you can't go back over a letter
// repeatedly (e.g., SPURT is a valid solution for the provided
// grid, but SPURTS is not, since the S already got used once).
// If that assumption is invalid, a different approach is
// needed... and the problem becomes vastly more complicated,
// since any given string of fifty letters is not necessarily
// the end of your search since maybe there's a fifty-one
// letter word you haven't found, so you can only solve it
// through analysis of the word list you've been provided.

function AdjacentUnusedLocation(positions[], direction) {
  newpos = AdjacentLocation(positions.last, direction)
  if newpos == nil return nil
  if newpos in positions return nil
  return newpos
}

//////////////////////////////////////////////////////////////////////////

// For a given list of positions already explored, report it if it's a word,
// then see if adding one more position will make a word in each possible
// direction (excluding crossing back over places you've already been,
// or falling off the grid). This is a function that will recurse extensively,
// and is where the main work of the program is done.

function RecursePosition(positions[]) {

  // First, if this is a word, report it to the output.
  if IsAWord(positions) print PositionsToString(positions)
  // Doing this first ensures single-letter words are found (e.g., I)

  // If the grid allows the same word to be created by differing
  // paths, it will be reported each time. For instance, in
  // the supplied grid, LYE can be made two ways (5 8 9 and 5 8 12)
  // and so will be listed twice. I consider this a feature, but
  // if it's considered a bug, you could always pipe the output
  // into uniq! (Or solve it with an internal cache, but that's a
  // much less modular solution, so I haven't done that here.)

  // Next, if the list is already sixteen elements, take an early exit
  // Note: if there are no valid directions, we won't recurse anyway,
  // so this is just an optimization, and the code would work without
  // it (ideally we'd prove this with red-green refactoring).
  if positions.size == TheGrid.size return

  // For each possible direction, try adding that direction
  for direction = 0 to 7 {
    newpos = AdjacentUnusedLocation(positions, direction)
    if newpos != nil {
      newpositions = positions.append(newpos) // array push, e.g., << in Ruby
      RecursePositions(newpositions)
    }
  }
}

//////////////////////////////////////////////////////////////////////////

// The main function simply starts the recursion in each of the sixteen
// possible starting positions. I'm assuming something else in that
// missing gist might be what already loaded TheGrid[].

public FindAllWordsInGrid() {
  for starting = 0 to 15 {
    positions = [starting] // craeate new array with one element
    RecursePosition(positions)
  }
}</code></pre>

app/views/static_pages/home.html.erb
<table border=0 width="100%">
  <tr>
    <td>
      <table rows=4 cols=4 border=1>
        <tr><td>D</td><td>G</td><td>H</td><td>I</td></tr>
        <tr><td>K</td><td>L</td><td>P</td><td>S</td></tr>
        <tr><td>Y</td><td>E</td><td>U</td><td>T</td></tr>
        <tr><td>E</td><td>O</td><td>R</td><td>N</td></tr>
      </table>
    </td>
    <td>buttons and list go here</td>
  </tr>
</table>